server:
  port: 10000
spring:
  application:
    name: Gateway
  cloud:
    nacos:
      discovery:
        server-addr: 43.134.18.178:8848
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:8080
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowedCredentials: true
      routes:
        - id: oa_user
          uri: lb://oa-user
          predicates:
            - Path=/api/user/**
